### PR TITLE
Automatic version checking

### PR DESCRIPTION
**Pull request by SELEKCJONER**
This commits adds automatic version checker for .skel files removing the need for exceptions in loader.vue and version lines in l2d.json.
Does not affect custom spine loader.

### CODE REVIEW

**Comment by Koshirei** [comment]
In this current state, I totally understand the need for such a code to be made and used.

However I cannot accept the current code as there is a duplication of network queries toward NIKKE-DB-LEGACY;

image

You make a request for the skel to grab the spine version, saves it to an array buffer, and let's the spine runtime do another request to the skel, making two times the same query in the end (Loader.vue:82) , which is pretty bad for the user experience.

I will be trying on my end if we can use the ArrayBuffer or the uint8array as a rawDataUri similarly to the custom spine loader

**Comment by Koshirei** [comment]
welp I've tried the entire evening converting the ArrayBuffer and uint8array to a working DataURI but I could never make it work. the XMLHttpRequest seems to send a broken response with some chars being replaced and breaking all possible convertion.
(the xmlhttprequest have a ArrayBuffer of length 92000, but for the custom spine import of the same file it's 93000)

**Comment by Koshirei** [comment]
@SELEKCJONER can you review this commit? 
I have changed your XMLHttpRequest to make it retrieve an ArrayBuffer as a response, which doesn't break it as I mentionned in my second comment. ( that new response's ArrayBuffer have a length of 93000 as needed )
That way we already have the content we need ( before a convertion to DataUri ) to avoid doing a double network query toward legacy for the skel file.

**Comment by SELEKCJONER** [comment]
Your change somehow makes me get this error after i change to a different character after first loading up rapi
`Uncaught TypeError: Cannot read properties of null (reading 'height')
    at Loader.vue?t=1717156692171:325:31`
    
    The only time i was getting such error before was when code tried to access .spine-player-canvas element before it was loaded or when i got spine error that made it unable to load player canvas
    
    I will try to fix it but your help is welcome.

**Comment by SELEKCJONER** [comment]
I think its fixed now there are no double requests and canvas error doesnt show up

**Comment by SELEKCJONER** [comment]
Now any 4.1x and 4.0x files should work thanks to regex

**Comment by Koshirei** [comment]
looks good. I wouldn't have corrected the undefined canvas that way but if it works, it works.

I'll give it a small test after work and I will accept the PR right after

**Comment by Koshirei** [comment]
the spine loading spinner is not centered in the app 
image

I'm not sure if it comes from your fix or mine. I'll give it a fix right now before accepting the pr

**Comment by Koshirei** [comment]
Thanks for the feature. I will be adding you in the website credits when I'll find some time to put up the new event. do you wish of a custom color as the background of your name? send me the rgb or hex

**Comment by SELEKCJONER** [comment]
well it would be nice if i could get `linear-gradient(170deg, #07137d, #611e0d)` as background but if i am restricted to single color then i will take `#260b56`

**Pull request merged**
