### PR TITLE
record animations as webm

### PR DESCRIPTION
**Pull request by cinderisles**
WIP branch for #4 

I hacked together some really basic animation recording capabilities. Yeah, the styling is awful for now. I'm looking for feedback on what the final UI should look like

I added a Record button to the tool list on the right

I was thinking maybe the recordings could get saved in a list and the user can click to playback each one and right click to save. or maybe I add a download button too. The list could just be stored in their browser

I'll need to add controls for bitrate and such. I just used30 FPS and 24 Mbps for fun, but we could give the user more control over it

### CODE REVIEW

**Comment by cinderisles** [comment]
I decided I'm going to make a generic lib for recording videos from a canvas element while maintaining transparency

I've got some more ideas I want to experiment with and dont want to pollute your repo with stuff you might not want some I'm closing this for now

**Comment by digisomni** [comment]
I've managed to add it with transparency it looks like.

**Comment by cinderisles** [comment]
@digisomni hey, awesome work 🎉  what browser are you using? At least with my version of Firefox I wasnt able to get the VP8 or 9 codec working so was looking into other solutions

**Comment by digisomni** [comment]
Ah, okay, so I am using Chrome and maybe that's partly part of the problem. Chromium added support for this, I think we can just put a tooltip on the button that says "Chrome and Safari only".

However, I was unable (so far) to get the animation to loop perfectly with the recording so no editing is needed, maybe you could help take a stab at that? It's timing issues, and maybe just bad logic on my part.

Essentially, playing the animation does not *start* the animation immediately but the recording does, or, maybe it's the other way around, either way, they're out of sync causing there to be a jitter for the loop.

Alternatively we can scrap WebM entirely and try to capture the frames from the canvas directly at a fixed rate of 60 FPS and then use a library to convert that to WebP at the end.

**Pull request closed without merging**
